name: heart_disease_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12   
  - pip
  - pip:
    - mlflow
    - cloudpickle
    - numpy
    - pandas
    - psutil
    - pyarrow
    - scikit-learn
    - scipy
    - matplotlib  
    - seaborn     